    <!-- Docs nav
    ================================================== -->
    <BR/>
    <div class="row">
      <div class="span2 sidebar">

<?php echo $this -> partial('admin/sidebar.phtml');?>
      </div>
      <div class="span9">
          <div id="view-content" class="shadowbox">
    <h3>Add a Student</h3>
    <p class="error"></p>
	<?= $this->studform; ?>
</div>
      </div>
    </div>