    <!-- Docs nav
    ================================================== -->

      <div class="span2 sidebar">

<?php echo $this -> partial('student/sidebar.phtml');?>
      </div>
    <div id="content" class="box-content span9 sortable ui-sortable">
        <!-- File structure
        ================================================== -->
        
          <div class="page-header">
            <h1>Welcome Admin,</h1>
          </div>
          <p class="lead">Your dream to build careers of many young minds begins here. Educulas ia all about enriching others dreams. Thanks for signing up.<BR/>

</p>

<BR/><BR/>

1. Setup your school now<BR/><BR/>
2. Find how your wards are faring<BR/><BR/>
3. Get in touch with your staffs, professors, students and parents.<BR/><BR/>
</section>

  </div>

