    <!-- Docs nav
    ================================================== -->
    <div class="row">
      <div class="span3 sidebar">
        <?php echo $this -> partial('/admin/sidebar.phtml');?>
      </div>
      <div class="span9">

        <!-- File structure
        ================================================== -->
        <section id="file-structure">
          <div class="page-header">
            <h1>Welcome Admin,</h1>
          </div>
          <p class="lead">Manage Students<BR/>

</p>

<BR/><BR/>





<div class="row-fluid">

              <div class="span4">
              <a class="btn btn" href="student/view" >View Students >></a>
              <p>When you are running a campus of more than thousand colleagues, finding their details gets difficult, not so with educulas.</p>
              </div>

            <div class="span4">
            <a class="btn btn-success" href="student/create" >Add Student >></a>
              <p>When somebody new joins the team, all you need to do is create a new account for them.</p>
            </div>

            <div class="span4">
              <a class="btn btn-danger" href="student/delete" >Delete Student >></a>
              <p>Some of your staffs are moving out, ok, we don't delete their stuffs, we move them to archive.</p>
            </div>

          </div>









<BR/><BR/>










<BR/><BR/>




                  </section>







      </div>
    </div>