    <!-- Docs nav
    ================================================== -->
 
      <div class="span2 main-menu-span">
        <?php echo $this -> partial('/admin/sidebar.phtml');?>
      </div>
    <div id="content" class="span9">
          <div id="view-content" class="shadowbox">
        <!-- File structure
        ================================================== -->
        <section id="file-structure">
          <div class="page-header">
            <h1>Welcome Admin,</h1>
          </div>
          <p class="lead">Manage Students<BR/>

</p>

<BR/><BR/>





<div class="row-fluid">

              <div class="span4">
              <a class="btn btn" href="#" >View Students >></a>
              </div>

            <div class="span4">
            <a class="btn btn-success" href="student/create" >Add Student >></a>
             </div>

            <div class="span4">
              <a class="btn btn-danger" href="#" >Delete Student >></a>
             </div>

          </div>









<BR/><BR/>










<BR/><BR/>




                  </section>




      </div>


      </div>
   