    <!-- Docs nav
    ================================================== -->
     <?php
        $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
 ?>
    <br/>
    <div class="row">
      <div class="span2 sidebar">

              <?php echo $this -> partial('admin/sidebar.phtml');?>
      </div>

        <div class="span10">

          <div class="shadowbox dashboard" id="view-content">
              <div class="span9">
            <h3>Attendance</h3>
            <?= $this->attendanceform; ?>
             <fieldset id="fieldset-col3" class="">
              <div class="control-group">
                  <label for=".ajaxLink1" class="control-label optional"></label>
                  <div class="controls">

       <?php

       echo $this->ajaxLink('load',
      'attendance/show',
      array('update' => '.agrid',
            'form'=>'.form-vertical',
            'attribs' => array('class' => 'btn btn-primary','data-loading-text' => 'Loading...'),
             'method' => 'post'),
      array('dataType' => 'json')
      );

       ?>
                  </div>
              </div>
          </fieldset>
              </div>
              <div class="agrid span9">

        </div>

            </div>

      </div>

    </div>