<!DOCTYPE HTML>
<html>
<head>
    <title>attendance sheet</title>
 <?php
        $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
 ?>
 
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
    <link rel ="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/flick/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="<?=$baseUrl;?>/stuff/css/ui.jqgrid.css" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
    <script type="text/javascript" src="<?=$baseUrl;?>/stuff/js/i18n/grid.locale-en.js"></script>
    <script type="text/javascript">
	jQuery.jgrid.no_legacy_api = true;
    </script>
    <script type="text/javascript" src="<?=$baseUrl;?>/stuff/js/jquery.jqGrid.min.js"></script>

<style type="text/css">
        .tabgrid {
            font-size: 75%;
        }
</style>

<script type="text/javascript">
 //<![CDATA[
 
   jQuery(document).ready(function(){
var lastSel,mydata = <?=$this->data; ?>,

      grid=$("#list");
      
      grid.jqGrid({
            data:mydata,
            datatype:"local",
            colNames: <?= $this->colnames; ?>,
            colModel: <?= $this->colmodel; ?>,
            rowNum: 10000,
            sortname: 'stud',
            sortorder: 'asc',
            viewrecords: true,
            gridview: true,
            pager:"#pager",
            hoverrows:false,
            onSelectRow: function(id, e) {
                 jQuery("#list>#"+id).removeClass('ui-state-hover');
             },
            forcefit: true,
            shrinktofit:true,
            autowidth: true,
            cellurl:'url',
            cellEdit:true,
            cellsubmit: "clientArray",
	    height:"90%",
            caption:'Response: Attendance sheet for month <?=$this->month; ?>'
        });
       //  $("#list").jqGrid('navGrid','#pager',{edit:true,add:true,del:true,search:true});
        var gridData=jQuery("#list").jqGrid('getGridParam','data');
      $(".ui-jqgrid-titlebar").hide();

$(".savebtn").click(function(event){
    

   $.post("attendance/save",{grid:gridData,month:<?=$this->month?>,year:<?=$this->year?>,classy:<?=$this->classy?>},function(data){
          console.log(data);
   });

        event.preventDefault();

});
       
   });

 //]]>
    </script>
</head>
<body>

<table id="list">
</table>
    <div id="pager"></div>
    <a href="#" class="btn btn-primary savebtn">save</a>

</body>
</html>