<!DOCTYPE HTML>
<html>
<head>
    <title>attendance sheet</title>
 <?php
        $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
 ?>
 <script type="text/javascript" src="<?=$baseUrl;?>/stuff/js/i18n/grid.locale-en.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
    <link rel ="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/flick/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="<?=$baseUrl;?>/stuff/css/ui.jqgrid.css" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
    <script type="text/javascript" src="<?=$baseUrl;?>/stuff/js/jquery.jqGrid.min.js"></script>

<style type="text/css">
        .tabgrid {
            font-size: 75%;
        }
</style>

<script type="text/javascript">
 //<![CDATA[
  jQuery(document).ready(function(){

     var mydata = <?= $this->attdsheet; ?>;

        jQuery("#list").jqGrid({
            data: mydata,
            datatype: "local",
            colNames: <?= $this->colnames; ?>,
            colModel: <?= $this->colmodel; ?>,
            pager: '#pager',
            rowNum: 10,
            rowList: [5, 10, 20, 50],
            sortname: 'stud',
            sortorder: 'asc',
            viewrecords: true,
            gridview: true,
            forcefit: true,
            shrinktofit:true,
            autowidth: true,
            celledit : true,
            height:"90%",
            caption:'Response: Attendance sheet for month <?=$this->month; ?>'
        });
   });

 //]]>
    </script>
</head>
<body>

<table id="list">
</table>
<div id="pager"></div>

</body>
</html>