<!DOCTYPE HTML>
<html>
<head>
    <title>attendance sheet</title>
 <?php
        $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
 ?>
 <script type="text/javascript" src="<?=$baseUrl;?>/stuff/js/i18n/grid.locale-en.js"></script>    
 <link rel="stylesheet" type="text/css" href="<?=$baseUrl;?>/stuff/css/ui.jqgrid.css" />       
 <script type="text/javascript" src="<?=$baseUrl;?>/stuff/js/jquery.jqGrid.min.js"></script> 

<style type="text/css">
        .tabgrid {
            font-size: 75%;
        }
</style>

<script type="text/javascript">
 //<![CDATA[
 jQuery(document).ready(function(){
 

     var mydata = <?= $this->attdsheet; ?>;


        jQuery("#list").jqGrid({
            data: mydata,
            datatype: "local",
            colNames: <?= $this->colnames; ?>,
            colModel: <?= $this->colmodel; ?>,
            pager: '#pager',
            rowNum: 10,
            rowList: [5, 10, 20, 50],
            forceFit : true,
	    cellEdit: true,
	    cellsubmit: 'clientArray',
            viewrecords: true,
            gridview: true,
            shrinktofit:true,
            autowidth: true,
            scrollOffset:0,
            caption:<?= $this->month; ?>
        });
   });

 //]]>
    </script>
</head>
<body>

<table id="list">
</table>
<div id="pager"></div>    

</body>
</html>