<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Educulas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <?php echo $this->headLink(); ?>
    <?php echo $this->jQuery()
           ->setVersion('1.8')
           ->setUiVersion('1.8')
           ->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/flick/jquery-ui.css')
    ?>

    <?php echo $this->headLink(); ?>

    <?php

        $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();

        echo  $this->headLink()->appendStylesheet($baseUrl.'/stuff/css/mytheme.css');
        echo  $this->headLink()->appendStylesheet($baseUrl.'/stuff/css/mytheme-responsive.css');
        echo  $this->headLink()->appendStylesheet($baseUrl.'/stuff/css/docs.css');
        echo  $this->headLink()->appendStylesheet($baseUrl.'/stuff/js/google-code-prettify/prettify.css');
        
   ?>



    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/stuff/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/stuff/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/stuff/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/stuff/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/stuff/ico/apple-touch-icon-57-precomposed.png">

  </head>

  <body data-spy="scroll" data-target=".bs-docs-sidebar">

    <!-- Navbar
    ================================================== -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">

        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand pull-left" href="./index.html">Zend Demo</a>
          <div class="nav-collapse collapse">
          </div>
        </div>
      </div>

    </div>
<!-- Subhead
==================================================
<header class="jumbotron subhead" id="overview">
  <div class="container">
    <h1>General Information</h1>
    <p class="lead">Overview of the project, it's contents, and how to get started with a simple template.</p>
  </div>
</header>

-->

  <div class="container">
<?php echo $this->layout()->content; ?>
</div>


<footer>
<hr>
<center>All  Rights reserved &copy; 2012, This is footer</center>
</footer>
  <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    <script src="/stuff/js/jquery.js"></script>
    <script src="/stuff/js/google-code-prettify/prettify.js"></script>
    <script src="/stuff/js/mytheme-transition.js"></script>
    <script src="/stuff/js/mytheme-alert.js"></script>
    <script src="/stuff/js/mytheme-modal.js"></script>
    <script src="/stuff/js/mytheme-dropdown.js"></script>
    <script src="/stuff/js/mytheme-scrollspy.js"></script>
    <script src="/stuff/js/mytheme-tab.js"></script>
    <script src="/stuff/js/mytheme-tooltip.js"></script>
    <script src="/stuff/js/mytheme-popover.js"></script>
    <script src="/stuff/js/mytheme-button.js"></script>
    <script src="/stuff/js/mytheme-collapse.js"></script>
    <script src="/stuff/js/mytheme-carousel.js"></script>
    <script src="/stuff/js/mytheme-typeahead.js"></script>
    <script src="/stuff/js/mytheme-affix.js"></script>
    <script src="/stuff/js/application.js"></script>



  </body>
</html>
