<div class="container">
<?php

        $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
 ?>
    <h1><BR/></h1>`
    <p class="marketing-byline"></p>

    <div class="row">
      <div class="span4">
  
<strong></strong>
<p class="lead">

Educulas is a next generation learning initiative by Actuality.
</p> Learning initiatives must continuously innovate to remain competitive or to bring brighter pupils. See how our model can help your growth.

<BR/><BR/><a href="" class="btn btn-danger "><strong>Plans, Pricing and Signup</strong> <br/>Demo available for <em>free!</em></a>




      </div>
      <div class="span3">

      </div>
      <div class="span4">
          <div class="signin shadowbox">
              <h4>Sign in</h4>
               <div class="error"><?=$this->message;?></div>
              <?=$this->loginform; ?>

      </div>

<div class="clear"></div>
<!--<div id="shadowform"></div>-->

      </div>
      



</div>


</div>


