

<BR/>
<div class="container">



    <h1><BR/></h1>`
    <p class="marketing-byline"></p>

    <div class="row">
      <div class="span4">
<strong></strong>
<p class="lead">

Educulas is a next generation learning initiative by Actuality.
</p> Learning initiatives must continuously innovate to remain competitive or to bring brighter pupils. See how our model can help your growth.

<BR/><BR/><a href="" class="btn btn-danger "><strong>Plans, Pricing and Signup</strong> <br/>Demo available for <em>free!</em></a>




      </div>
      <div class="span4">

  &nbsp

      </div>
      <div class="span4">
          <div class="signin">

<p class="lead">
    Sign in
</p>
      <form class="form-inline">

 <input class="input-xlarge" type="text" placeholder="username">

<br/><br/>


<input type="password" class="input-xlarge" type="text" placeholder="password">


<br/>

<br/>


<button type="submit" class="btn btn-primary">Sign in</button></form>

      </div>

            <div class="clear"></div>
        <div style="position: absolute;
width: 434px;
z-index: -1;
margin-top: 5px;
background-image: url(http://zicedemo.com/images/shadowForm.png);
height: 33px;
margin-left: -20px;"></div>

      </div>
      



</div>





