<BR/><BR/><BR/><BR/><BR/><BR/>
<a href="staff.php" style="text-decoration : none;alink=black; link:black; vlink:black;color:black;"><i class="icon-stop"></i> Staffs</a><BR/>
<a href="course.php" style="text-decoration : none;alink=black; link:black; vlink:black;color:black;"><i class="icon-th-list"></i> Course</a> <BR/>
<a href="parents.php" style="text-decoration : none;alink=black; link:black; vlink:black;color:black;"><i class="icon-user"></i> Parents</a> <BR/>
<a href="students.php" style="text-decoration : none;alink=black; link:black; vlink:black;color:black;"><i class="icon-search"></i> Students</a> <BR/>
<a href="notifications.php" style="text-decoration : none;alink=black; link:black; vlink:black;color:black;"><i class="icon-bullhorn"></i> Notifications</a> <BR/>
<a href="statistics"style="text-decoration : none;alink=black; link:black; vlink:black;color:black;"><i class="icon-signal"></i> Statistics</a> <BR/>
<HR/>

<BR/><BR/>
<a href="logout.php" style="text-decoration : none;alink=black; link:black; vlink:black;color:black;"><i class="icon-off"></i> Logout</a> <BR/>
<a href="help.php"style="text-decoration : none;alink=black; link:black; vlink:black;color:black;"><i class="icon-search"></i> Help</a> <BR/>