    <!-- Docs nav
    ================================================== -->
      <div class="span2 sidebar">
        <?php echo $this -> partial('/admin/sidebar.phtml');?>
      </div>
      <div id="content" class="span9">

        <!-- File structure
        ================================================== -->
      
          <div class="page-header">
            <h1>Welcome Admin,</h1>
          </div>
          <p class="lead">Manage Staff<BR/>

</p>

<BR/><BR/>





<div class="row-fluid">

              <div class="span4">
              <a class="btn btn" href="#" >View Staffs >></a>
              </div>

            <div class="span4">
            <a class="btn btn-success" href="staff/createprofile" >Add Staff >></a>
              </div>

            <div class="span4">
              <a class="btn btn-danger" href="#" >Delete Staff >></a>
              </div>

          </div>
      </div>








<BR/><BR/>




                  </section>







      </div>
  