    <!-- Docs nav
    ================================================== -->
    <div class="row">
      <div class="span2 sidebar">

<?php echo $this -> partial('/admin/sidebar.phtml');?>
      </div>
      <div class="span9">
          <div class="shadowbox dashboard" id="view-content">
        <!-- File structure
        ================================================== -->
        <section id="file-structure">
          <div class="page-header">
            <h1>Welcome admin,</h1>
          </div>
          <p class="lead">Your dream to build careers of many young minds begins here. Educulas is all about enriching others' dreams. Thanks for signing up.<BR/>

</p>

<BR/><BR/>

1. Setup your school now<BR/><BR/>
2. Find how your wards are faring<BR/><BR/>
3. Get in touch with your staffs, professors, students and parents.<BR/><BR/>
</section>

  </div>
    </div>
    </div>