<div class="marketing">

    
    <p class="marketing-byline">
      
    </p>

    <div class="row">
      <div class="span4">    &nbsp
          
      </div>
      <div class="span4">
          <h3> Administration Login</h3>
          <div class="signin">

<p class="lead"></p>


      <form class="form-inline">

 <input class="input-xlarge" type="text" placeholder="Username"  value="">

<br/><br/>


<input type="password" class="input-xlarge" type="text" placeholder="Password" value="">


<br/><br/>

<label class="checkbox"> <input type="checkbox">
Remember me </label>

<br/>


<input type="submit" class="btn btn-primary" value="Sign in" />
         

      </form>
 </div>



      </div>
      <div class="span4">


      <p class="lead">
    &nbsp


</p>
      </div>


</div>

    </div>