<div class="marketing">

 <?php

          $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
    <p class="marketing-byline">

    </p>

    <div class="row">
      <div class="span4">    &nbsp

      </div>
        
        <div class="span4 adminbox" style="text-align: center;margin-top:10%;" >
            
            <h3 style="color:orange">Admin Login</h3>
         
          <div class="signin " style="text-align: left;">

<p class="error"><?=$this->message;?></p>

<?= $this->loginform; ?>

 </div>



      </div>
      <div class="span4">


      <p class="lead">
    


</p>
      </div>


</div>

    </div>