<div class="marketing">


    <p class="marketing-byline">

    </p>

    <div class="row">
      <div class="span4">    &nbsp

      </div>
        <div class="span4" >
          <h3> Administration Login</h3>
          <div class="signin" style="text-align: left;">

<p class="error"><?=$this->message;?></p>

<?= $this->loginform; ?>

 </div>



      </div>
      <div class="span4">


      <p class="lead">
    &nbsp


</p>
      </div>


</div>

    </div>